name: coffee_shop_get
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get:
  intl:
  get_storage:
  badges:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
   - images/
   - images/cats/
   - images/coffee/
   - images/juice/
   - images/tea/
   - images/social/
